2023-06-19 09:29:21,275 INFO    StreamThr :18722 [internal.py:wandb_internal():88] W&B internal server running at pid: 18722, started at: 2023-06-19 09:29:21.259414
2023-06-19 09:29:21,280 DEBUG   HandlerThread:18722 [handler.py:handle_request():138] handle_request: status
2023-06-19 09:29:21,289 DEBUG   SenderThread:18722 [sender.py:send_request():317] send_request: status
2023-06-19 09:29:21,294 INFO    WriterThread:18722 [datastore.py:open_for_write():75] open: saved_models/codeparrot-clean/2023-06-19_09-29-09/wandb/offline-run-20230619_092921-1jf4j2wg/run-1jf4j2wg.wandb
2023-06-19 09:29:21,295 DEBUG   HandlerThread:18722 [handler.py:handle_request():138] handle_request: run_start
2023-06-19 09:29:21,310 DEBUG   HandlerThread:18722 [meta.py:__init__():34] meta init
2023-06-19 09:29:21,311 DEBUG   HandlerThread:18722 [meta.py:__init__():49] meta init done
2023-06-19 09:29:21,311 DEBUG   HandlerThread:18722 [meta.py:probe():215] probe
2023-06-19 09:29:21,321 DEBUG   HandlerThread:18722 [git.py:repo():40] git repository is invalid
2023-06-19 09:29:21,321 DEBUG   HandlerThread:18722 [meta.py:_save_pip():53] save pip
2023-06-19 09:29:21,329 DEBUG   HandlerThread:18722 [meta.py:_save_pip():67] save pip done
2023-06-19 09:29:21,331 DEBUG   HandlerThread:18722 [meta.py:_save_conda():74] save conda
2023-06-19 09:29:29,207 DEBUG   HandlerThread:18722 [meta.py:_save_conda():84] save conda done
2023-06-19 09:29:29,207 DEBUG   HandlerThread:18722 [meta.py:probe():253] probe done
2023-06-19 09:34:26,421 INFO    MainThread:18722 [internal.py:handle_exit():78] Internal process exited
2023-06-19 09:34:26,422 WARNING MsgRouterThr:18722 [router.py:message_loop():74] EOFError seen in message_loop
